image: maven:3.3.3-jdk-8
git:
  path: github.com/fabgia/wizardry
script:
  - echo "build commands"
  - .shipped/build
  - .shipped/test
clone:
  path: github.com/fabgia/wizardry
build:
  image: maven:3.3.3-jdk-8
  commands:
    - echo "build commands"
    - .shipped/build
    - .shipped/test
publish:
  docker:
    file: ./Dockerfile
    insecure: true
    username: $$docker_user
    password: $$docker_key
    registry: $$docker_registry
    repo: $$docker_repo
    email: $$docker_user_email
    tag: $$COMMIT
    
